# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(date:yyyy).$(Month)$(rev:.r)

steps:

- script: yarn install

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'android/gradlew'
    workingDirectory: 'android/'
    options: '-PversionName=$(PversionName) -PversionCode=$(PversionCode)'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: '$(KeyStorePassword)'
    apksignerKeystoreAlias: '$(KeyAlias)'
    apksignerKeyPassword: '$(KeyPassword)'
    zipalign: false

- task: PublishBuildArtifacts@1
  inputs:
    # PathtoPublish: 'android/app/build/outputs/apk/release'
    PathtoPublish: 'android/app/build/outputs/'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'appcenter'
    appSlug: 'SampleAndroidApplication'
    appFile: 'android/app/build/outputs/apk/release/NavigationSample-release-1.0.0.apk'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Here are the release notes for this version.'
    destinationType: 'groups'
    distributionGroupId: '47e8accb-4b28-40d5-a327-d126cb570703'